"""Minimal smoke test for scripts/run_gui.py's Simulator- and Hardware-mode
composition functions.

Confirms:
- a QApplication can exist in this process
- MainWindow can be constructed and shown against the launcher's own
  build_simulator_runtime()/build_hardware_runtime() composition
- data generated by the registered SimulatorDevice reaches the UI
- Hardware mode wires SerialChannel -> HardwareDeviceReceiver ->
  HardwareRuntimeRunner into the *same* ApplicationRuntime.data_service
  MainController/UI already read from, and that a manual runner.run_once()
  (standing in for what a QTimer would call repeatedly) delivers data to
  the UI exactly like Simulator mode does

Does not call scripts.run_gui.main() itself: main() calls app.exec(),
which blocks the process running the GUI event loop until the window is
closed. Instead this test reuses main()'s own composition helpers and
drives MainWindow directly -- exactly how tests/ui/test_main_window.py
already exercises MainWindow elsewhere in this suite. Hardware mode is
exercised with mocked pyserial (same technique as
tests/communication/test_serial.py), since no real hardware is available.
"""

from __future__ import annotations

import json
from types import SimpleNamespace
from unittest.mock import patch

from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QApplication

from api.local_api import LocalApi
from application.hardware_runtime import DATA_REPORT_CODE
from protocol.encoder import encode
from protocol.frame import Frame
from scripts.run_gui import build_hardware_runtime, build_simulator_runtime
from ui.controller import MainController
from ui.main_window import MainWindow


def test_qapplication_can_be_created(qtbot) -> None:
    assert QApplication.instance() is not None


def test_main_window_can_be_shown_with_launcher_composition(qtbot) -> None:
    runtime, _runner = build_simulator_runtime()
    controller = MainController(LocalApi(runtime), client_id="test-launcher")
    window = MainWindow(controller)
    qtbot.addWidget(window)

    window.show()

    assert window.isVisible()
    window.close()


def test_launcher_registers_the_three_environmental_sensors(qtbot) -> None:
    """Simulator mode must report the same three channels Hardware mode
    does, so the window's metric cards and alarms work without a board."""
    runtime, _runner = build_simulator_runtime()

    assert runtime.list_devices() == [
        "sim-env-1-temp",
        "sim-env-1-humi",
        "sim-env-1-noise",
    ]


def test_simulator_runner_drives_data_into_the_ui(qtbot) -> None:
    """The regression this guards: before 2026-08-15 nothing in the
    running application called report_data(), so Simulator mode showed a
    permanently empty window. Driving the returned runner must populate
    the data panel."""
    runtime, runner = build_simulator_runtime()
    controller = MainController(LocalApi(runtime), client_id="test-launcher")
    window = MainWindow(controller)
    qtbot.addWidget(window)
    window.show()

    window._device_list.setCurrentRow(0)
    window._control_panel._channel_input.setCurrentText("temperature")
    qtbot.mouseClick(window._control_panel._subscribe_button, Qt.MouseButton.LeftButton)

    runner.run_once()

    assert window._data_panel.row_count() == 1
    assert float(window._data_panel._latest_table.item(0, 2).text()) > 0
    # **必须收尾关窗**，不是礼貌而是防崩（2026-09-21 定位）。
    # 一个 show() 过、且刚喂进数据的窗口，会留下一个尚未处理的 paint 事件；
    # pytest-qt 在用例结束后先 _process_events()、随后销毁 addWidget 登记的
    # 控件，那个 paint 便可能落在已开始析构的控件上，表现为
    # `Windows fatal exception: access violation`，栈顶在
    # `chart_widget._draw_grid` —— 整个 pytest 进程当场死掉，**没有失败用例、
    # 没有统计行**，看起来像是随机的环境问题。
    #
    # 它对用例总数敏感：本文件之外随便再加四个用例（哪怕是 `assert True`）
    # 就能稳定复现，所以它多年来一直擦着边过。三个 show() 过窗口的用例里
    # 只有喂过数据的会崩——空图表那条 `_draw` 早早返回，画不到 _draw_grid。
    window.close()


def test_simulator_runner_targets_all_three_channels(qtbot) -> None:
    runtime, runner = build_simulator_runtime()

    points = runner.run_once()

    assert {point.channel for point in points} == {
        "temperature",
        "humidity",
        "noise",
    }


# ---------------------------------------------------------------------------
# Hardware mode: build_hardware_runtime()
# ---------------------------------------------------------------------------


class _FakeSerialPort:
    """Minimal virtual stand-in for serial.Serial (mirrors
    tests/communication/test_serial.py's own fake). Reads and writes share
    one buffer, modeling "bytes written to the wire are what get read back"
    for test purposes."""

    def __init__(self) -> None:
        self.is_open = True
        self.buffer = bytearray()

    def write(self, data: bytes) -> int:
        self.buffer.extend(data)
        return len(data)

    @property
    def in_waiting(self) -> int:
        return len(self.buffer)

    def read(self, size: int) -> bytes:
        chunk = bytes(self.buffer[:size])
        del self.buffer[:size]
        return chunk

    def close(self) -> None:
        self.is_open = False


def _build_hardware_runtime_with_mocked_serial():
    with patch(
        "communication.serial.list_ports.comports",
        return_value=[SimpleNamespace(device="COM3")],
    ):
        with patch(
            "communication.serial.serial.Serial", return_value=_FakeSerialPort()
        ):
            return build_hardware_runtime(port="COM3", device_id="mcu-1")


def test_build_hardware_runtime_registers_the_remote_device(qtbot) -> None:
    runtime, _runner = _build_hardware_runtime_with_mocked_serial()
    assert runtime.list_devices() == ["mcu-1"]


def test_build_hardware_runtime_runner_starts_not_running(qtbot) -> None:
    _runtime, runner = _build_hardware_runtime_with_mocked_serial()
    assert runner.running is False


def test_hardware_mode_data_reaches_the_ui_via_runner_run_once(qtbot) -> None:
    runtime, runner = _build_hardware_runtime_with_mocked_serial()
    controller = MainController(LocalApi(runtime), client_id="test-launcher")
    window = MainWindow(controller)
    qtbot.addWidget(window)
    window.show()

    window._device_list.setCurrentRow(0)
    window._control_panel._channel_input.setCurrentText("temperature")
    qtbot.mouseClick(
        window._control_panel._subscribe_button, Qt.MouseButton.LeftButton
    )

    # Simulate "the MCU wrote a data-report frame to the wire" by sending
    # through the device's registered channel, then let runner.run_once()
    # do what a QTimer tick would do in the real GUI.
    registration = runtime.devices.get("mcu-1")
    payload = json.dumps({"channel": "temperature", "value": 25.5}).encode("utf-8")
    frame = Frame(
        device_id=registration.wire_id,
        command_type=DATA_REPORT_CODE,
        payload=payload,
    )
    registration.channel.send(encode(frame))

    runner.start()
    runner.run_once()

    assert window._data_panel.row_count() == 1
    # 2026-09-18: 温度按两位小数显示（ui/channel_display.CHANNEL_DECIMALS），
    # 所以这里断言的是渲染后的文本；上链路送来的仍是 25.5 这个原值。
    assert window._data_panel._latest_table.item(0, 2).text() == "25.50"
    window.close()  # 同上：喂过数据的窗口不关，teardown 时可能崩在 paint 里


def test_hardware_mode_device_channels_are_watched_for_alarms(qtbot) -> None:
    """Regression test: build_hardware_runtime() calls
    ``runtime.devices.register(...)`` directly (to read back the wire id),
    bypassing ApplicationRuntime.register_device() -- which would
    otherwise auto-subscribe the alarm processor. build_hardware_runtime()
    must therefore call ``runtime.watch_alarms_for(device)`` itself, or
    Hardware-mode devices silently never produce any alarm/status events
    at all (caught via manual testing 2026-08-12: the WSL hardware-in-the-
    loop demo showed no alarm even for an out-of-threshold reading, while
    Simulator mode worked). See application/runtime.py's watch_alarms_for
    docstring.
    """
    from service.sensor_data_processor import ThresholdStatus

    runtime, runner = _build_hardware_runtime_with_mocked_serial()
    statuses: list[ThresholdStatus] = []
    runtime.subscribe_alarm_status(statuses.append)

    registration = runtime.devices.get("mcu-1")
    payload = json.dumps({"channel": "temperature", "value": 40.0}).encode("utf-8")
    frame = Frame(
        device_id=registration.wire_id,
        command_type=DATA_REPORT_CODE,
        payload=payload,
    )
    # 送两帧：2026-09-09 起报警需连续确认，一次越限只是嫌疑。
    registration.channel.send(encode(frame))
    registration.channel.send(encode(frame))

    runner.start()
    runner.run_once()

    assert len(statuses) == 2
    assert [s.triggered for s in statuses] == [False, True]
    assert statuses[-1].channel == "temperature"


def test_simulator_devices_each_declare_only_their_own_channel() -> None:
    """Simulator mode registers three one-channel devices, Hardware mode
    one three-channel device. A view that offers a fixed三通道 list is
    therefore wrong in Simulator mode -- two of every three choices
    subscribe to nothing while reporting success. The channel list has to
    come from the device, so it has to be observable through the API."""
    from api.local_api import LocalApi

    runtime, _ = build_simulator_runtime()
    api = LocalApi(runtime)

    seen = {
        device_id: api.get_device_status(device_id).channels
        for device_id in api.list_devices()
    }

    assert len(seen) == 3
    for channels in seen.values():
        assert len(channels) == 1
    assert sorted(c for pair in seen.values() for c in pair) == [
        "humidity",
        "noise",
        "temperature",
    ]


def test_subscribing_a_channel_the_device_lacks_yields_no_data() -> None:
    """Documents the trap the channel list exists to prevent: this is not
    an error at any layer, it simply never delivers anything."""
    from api.local_api import LocalApi

    runtime, runner = build_simulator_runtime()
    api = LocalApi(runtime)
    temperature_device = next(
        d for d in api.list_devices()
        if api.get_device_status(d).channels == ("temperature",)
    )

    received: list[object] = []
    subscription = api.subscribe_data(
        temperature_device, "humidity", received.append
    )
    runner.start()
    for _ in range(5):
        runner.run_once()

    assert subscription  # accepted without complaint
    assert received == []  # and delivers nothing, forever
